export class ShoesTestData {
    static manageData = [
        {
          "id": "615f59c46fd830d8b1151488",
          "size": 6,
          "color": "green",
          "brand": "Nike",
          "type": "Cycling shoe",
          "category": "Jeans",
          "price": "1,792",
          "picture": "shoe-9",
          "idealFor": "Boys",
          "name": "Nike Cycling shoe",
          "registered": "2018-11-30T11:08:28"
        },
        {
          "id": "615f59c4524a6a4a968c310b",
          "size": 13,
          "color": "green",
          "brand": "Bata",
          "type": "Golf shoe",
          "category": "Sports shoe",
          "price": "3,224",
          "picture": "shoe-4",
          "idealFor": "Men",
          "name": "Bata Golf shoe",
          "registered": "2019-07-11T17:35:49"
        },
        {
          "id": "615f59c4c3a3a930462fb1a9",
          "size": 10,
          "color": "yellow",
          "brand": "Nike",
          "type": "Golf shoe",
          "category": "Tshirt",
          "price": "3,433",
          "picture": "shoe-14",
          "idealFor": "Men",
          "name": "Nike Golf shoe",
          "registered": "2015-07-16T17:56:34"
        },
        {
          "id": "615f59c484532bdd0ee91034",
          "size": 14,
          "color": "green",
          "brand": "Puma",
          "type": "Running shoe",
          "category": "Track pant",
          "price": "2,824",
          "picture": "shoe-9",
          "idealFor": "Girls",
          "name": "Puma Running shoe",
          "registered": "2018-10-08T14:00:20"
        },
        {
          "id": "615f59c454795e28406c0da5",
          "size": 8,
          "color": "yellow",
          "brand": "Bata",
          "type": "Tennis shoe",
          "category": "Top",
          "price": "1,827",
          "picture": "shoe-1",
          "idealFor": "Women",
          "name": "Bata Tennis shoe",
          "registered": "2018-03-02T03:56:00"
        },
        {
          "id": "615f59c43390951547a31128",
          "size": 15,
          "color": "pink",
          "brand": "Puma",
          "type": "Golf shoe",
          "category": "Tight",
          "price": "1,353",
          "picture": "shoe-12",
          "idealFor": "Women",
          "name": "Puma Golf shoe",
          "registered": "2018-12-15T07:16:15"
        },
        {
          "id": "615f59c4b962abb94ae1dab5",
          "size": 9,
          "color": "blue",
          "brand": "Reebok",
          "type": "Cycling shoe",
          "category": "Track pant",
          "price": "2,951",
          "picture": "shoe-15",
          "idealFor": "Girls",
          "name": "Reebok Cycling shoe",
          "registered": "2019-01-18T08:21:04"
        },
        {
          "id": "615f59c4bf74e8d61b9af4c7",
          "size": 9,
          "color": "red",
          "brand": "VKC",
          "type": "Cricket shoe",
          "category": "Tight",
          "price": "2,379",
          "picture": "shoe-15",
          "idealFor": "Girls",
          "name": "VKC Cricket shoe",
          "registered": "2018-01-27T10:37:14"
        },
        {
          "id": "615f59c49b2bf572953a5f98",
          "size": 7,
          "color": "blue",
          "brand": "Nike",
          "type": "Cycling shoe",
          "category": "Shirt",
          "price": "3,727",
          "picture": "shoe-3",
          "idealFor": "Girls",
          "name": "Nike Cycling shoe",
          "registered": "2019-06-26T06:09:47"
        },
        {
          "id": "615f59c421a59fc812653c66",
          "size": 8,
          "color": "yellow",
          "brand": "VKC",
          "type": "Golf shoe",
          "category": "Tight",
          "price": "2,091",
          "picture": "shoe-5",
          "idealFor": "Boys",
          "name": "VKC Golf shoe",
          "registered": "2021-06-10T04:12:02"
        },
        {
          "id": "615f59c4c566d198fbf80652",
          "size": 10,
          "color": "red",
          "brand": "Bata",
          "type": "Cricket shoe",
          "category": "Track pant",
          "price": "1,861",
          "picture": "shoe-16",
          "idealFor": "Boys",
          "name": "Bata Cricket shoe",
          "registered": "2018-09-12T23:42:16"
        },
        {
          "id": "615f59c4660e56ce6a0cc918",
          "size": 11,
          "color": "pink",
          "brand": "Crocs",
          "type": "Running shoe",
          "category": "Mens Footwear",
          "price": "1,239",
          "picture": "shoe-10",
          "idealFor": "Women",
          "name": "Crocs Running shoe",
          "registered": "2014-06-21T16:09:50"
        },
        {
          "id": "615f59c47327240ff43b9ace",
          "size": 8,
          "color": "green",
          "brand": "Addidas",
          "type": "Cricket shoe",
          "category": "Mens Footwear",
          "price": "1,009",
          "picture": "shoe-9",
          "idealFor": "Girls",
          "name": "Addidas Cricket shoe",
          "registered": "2017-09-18T07:27:55"
        },
        {
          "id": "615f59c4568e44bc1d5dfb34",
          "size": 6,
          "color": "brown",
          "brand": "Puma",
          "type": "Football shoe",
          "category": "Footwear",
          "price": "1,711",
          "picture": "shoe-15",
          "idealFor": "Girls",
          "name": "Puma Football shoe",
          "registered": "2018-06-29T11:48:31"
        },
        {
          "id": "615f59c480dcd78a74f613e4",
          "size": 14,
          "color": "brown",
          "brand": "Reebok",
          "type": "Cricket shoe",
          "category": "Tshirt",
          "price": "3,063",
          "picture": "shoe-7",
          "idealFor": "Women",
          "name": "Reebok Cricket shoe",
          "registered": "2021-09-20T01:34:22"
        },
        {
          "id": "615f59c4501ae2171d4b8db9",
          "size": 14,
          "color": "red",
          "brand": "Bata",
          "type": "Cycling shoe",
          "category": "Mens Footwear",
          "price": "2,212",
          "picture": "shoe-8",
          "idealFor": "Women",
          "name": "Bata Cycling shoe",
          "registered": "2015-03-25T02:09:27"
        },
        {
          "id": "615f59c445a734f40701d5e2",
          "size": 11,
          "color": "blue",
          "brand": "Bata",
          "type": "Tennis shoe",
          "category": "Footwear",
          "price": "3,550",
          "picture": "shoe-1",
          "idealFor": "Girls",
          "name": "Bata Tennis shoe",
          "registered": "2020-04-10T14:43:52"
        },
        {
          "id": "615f59c444c7dd0b10669c64",
          "size": 15,
          "color": "white",
          "brand": "Puma",
          "type": "Golf shoe",
          "category": "Tight",
          "price": "3,119",
          "picture": "shoe-16",
          "idealFor": "Men",
          "name": "Puma Golf shoe",
          "registered": "2014-12-21T20:55:21"
        },
        {
          "id": "615f59c4bd47be86e21aa4dc",
          "size": 6,
          "color": "green",
          "brand": "VKC",
          "type": "Cricket shoe",
          "category": "Tshirt",
          "price": "2,255",
          "picture": "shoe-1",
          "idealFor": "Men",
          "name": "VKC Cricket shoe",
          "registered": "2018-01-21T16:52:36"
        },
        {
          "id": "615f59c403e94b79cdca433d",
          "size": 14,
          "color": "green",
          "brand": "Reebok",
          "type": "Cycling shoe",
          "category": "Jeans",
          "price": "3,766",
          "picture": "shoe-13",
          "idealFor": "Boys",
          "name": "Reebok Cycling shoe",
          "registered": "2016-04-04T00:21:46"
        },
        {
          "id": "615f59c4fb0e6fb8bcb21dcf",
          "size": 13,
          "color": "yellow",
          "brand": "Reebok",
          "type": "Cycling shoe",
          "category": "Sports shoe",
          "price": "2,419",
          "picture": "shoe-5",
          "idealFor": "Men",
          "name": "Reebok Cycling shoe",
          "registered": "2017-11-12T02:40:55"
        },
        {
          "id": "615f59c4e80ac89b2f048304",
          "size": 11,
          "color": "blue",
          "brand": "VKC",
          "type": "Cycling shoe",
          "category": "Mens Footwear",
          "price": "3,270",
          "picture": "shoe-14",
          "idealFor": "Women",
          "name": "VKC Cycling shoe",
          "registered": "2017-08-10T16:51:45"
        },
        {
          "id": "615f59c47b6dbfc2a8c9fda4",
          "size": 11,
          "color": "green",
          "brand": "VKC",
          "type": "Football shoe",
          "category": "Sports shoe",
          "price": "2,891",
          "picture": "shoe-11",
          "idealFor": "Boys",
          "name": "VKC Football shoe",
          "registered": "2015-04-06T23:59:24"
        },
        {
          "id": "615f59c4d567387c39d0a7b9",
          "size": 10,
          "color": "brown",
          "brand": "Nike",
          "type": "Badminton shoe",
          "category": "Shorts",
          "price": "1,724",
          "picture": "shoe-12",
          "idealFor": "Girls",
          "name": "Nike Badminton shoe",
          "registered": "2019-11-13T01:35:51"
        },
        {
          "id": "615f59c4d4f4914363bf20b2",
          "size": 14,
          "color": "red",
          "brand": "Puma",
          "type": "Cricket shoe",
          "category": "Tight",
          "price": "3,571",
          "picture": "shoe-6",
          "idealFor": "Girls",
          "name": "Puma Cricket shoe",
          "registered": "2017-05-11T13:11:34"
        }
      ]
}